### ISSUE TITLE
Feature Request: Make nodemcu receive data through bluetooth and have a client on PC to send data using bluetooth

### ISSUE THREAD

**Issue by gui28347** [Bodmer/OpenWeather#38]
In some environments where you don't have wireless available, I think a good approach would be using bluetooth from a connected device sending data to nodemcu through bluetooth. Let me know if you think is a good idea.

Thanks,
Gui

**Comment by Bodmer** [comment]
If there are no other connection options that I guess it is a good idea for you. However it is  not something I would implement.

There maybe options you have not considered, for example a Windows 10 PC can be turned into a mobile hotspot to share an Ethernet connection and create a WiFi network.:
https://support.microsoft.com/en-us/windows/use-your-windows-pc-as-a-mobile-hotspot-c89b0fad-72d5-41e8-f7ea-406ad9036b85

You can also share an internet connection over bluetooth, so that might be a good option because the library uses TCPIP to get a connection with the server. However at the ESP32 (I am guessing that is what you have as the ESP8266 NodeMCU does not have bluetooth) you will need to load a bluetooth based TCPIP stack and that is not something I have tried.
