### ISSUE TITLE
Moon phase depiction for southern hemisphere

### ISSUE THREAD

**Issue by NigelTwo** [Bodmer/OpenWeather#42]
Those of us in the southern latitudes see the moon upside down, even though the moon phase is the same for everyone. Has this been overlooked when converting to .bmp moon icons?
Eichhorn has a function determineMoonIcon() that adjusts the index into the "moon fonts" depending on the defined latitude.

As to what happens at the equator, well, I get dizzy thinking about it :-( Perhaps that is a special case that could be handled by a comment in the code.

**Comment by Bodmer** [comment]
Good point. Will think further on this. A image file program such as MS Paint could be used to flip the images.

**Comment by NigelTwo** [comment]
The "data driven" design here has saved the day.
A comment next to where the long/lat settings are, would be all that is required. Thanks.

**Comment by Bodmer** [comment]
The visual orientation of the Moon rotates as an observer moves from the Northern to Southern lattitudes so the "real" view should rotate dependant on the lattitude,  time of day and the Moon distance from the elliptic etc! However by convention Moon phase calanders seem to all show the Moon in a particular orientation for the two hemispheres, so I think a simple set of 180 deg rotated images will be fine!

I will try to find time to sort this out in the next few days and also change to jpeg rather than bmp format to save space.
